### ISSUE TITLE
Eliminate "Idiomatic Jasper Bootstrapping"

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#475]
This is going to hurt, but having both the old FubuMVC-esque `JasperRuntime` and `IWebHostBuilder` model is setting us up for user confusion. Only support the WebHostBuilder model going forward.

Mostly going to be a nightmare for tests.

**Comment by jeremydmiller** [comment]
Not going to go exactly as far as I thought, but close. And I'm doing this for the alpha **now**

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Eliminate the JasperGenerationRules property on JasperRuntime
- [ ] Eliminate `IMessageContext` property on JasperRuntime
- [ ] JasperRuntime object implements `IJasperHost`

**Comment by jeremydmiller** [comment]
Still need to do the docs, but declaring victory otherwise
