### ISSUE TITLE
v0.9.9 Release Checklist

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#515]
Gotta look at what's missing

- [x] Document Postgresql as a message backing store
- [x] Document attributes for routing determination
- [x] Add Jasper.Persistence.Database to Nuget with all the necessary metadata
- [x] Update Appveyor versions
- [x] Update Jasper dependency versions in the templates
- [x] Update the Readme after the latest test rearrangements
- [x] Push 0.9.9 nugets
- [x] Write introductory blog post
- [x] Publish latest documentations

**Comment by jeremydmiller** [comment]
Done!
