### ISSUE TITLE
Replace all command line support with Oakton.AspNetCore and/or Lamar.Diagnostics

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#534]
We *might* consider using a separate Jasper.CommandLine nuget so folks don't have to take on the Oakton dependency. Maybe.

**Comment by jeremydmiller** [comment]
Also, replace all the environment check functionality with Oakton.AspNetCore as well

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Add reference to Oakton.AspNetCore
- [ ] Delete JasperInput
- [ ] Delete RunCommand
- [ ] Delete ServicesCommand
- [ ] Make JasperModuleAttribute inherit from OaktonCommandAssembly
- [ ] Delete all methods in `JasperAgent` related to command line usage
- [ ] Use `RunOaktonCommands()` as appropriate
- [ ] Delete the entire EnvironmentChecks namespace
- [ ] Clean up the documentation
