### ISSUE TITLE
Extract the HTTP support into a separate library

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#539]
Now, this is going to be fun. The big reason is that I want to be able to push just the command execution and messaging support to 1.0 first.

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Redo the "Describe" command to look through elements in the container rather than using `JasperRuntime`
- [ ] Cut the reference from `JasperRuntime` to `HttpSettings`
- [ ] Redo the `Code` command to pull elements from the container

## JasperHttp Project

- [ ] Start a new JasperHttp project
- [ ] Reference Jasper
- [ ] Pull over the Jasper.Http code
- [ ] Add an `IJasperExtension` that subsumes all the HTTP related DI registrations
- [ ] All other projects reference the new Jasper.Http project as needed
