### ISSUE TITLE
Advanced Exception Handling

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#554]
Inspired by a project at work. What if the system is hosed so badly that no message could possibly be processed? Shut the listener down altogether, find some way to "know" when it's available again.

I've got some notes somewhere on possible implementation. Find those, and add them here.

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Gotta ensure that the listener Uri is set on incoming envelopes, that or attach the `IListener`
- [ ] `IListener.Stop()`
- [ ] `IListener.Restart()` on each
- [ ] Add something to the compliance tests
- [ ] Use an in memory scheduled job? Or make a timeout in the listener itself?
- [ ] In compliance, check that all listeners say the status is Accepting on start up

**Comment by jeremydmiller** [comment]
## Vision

Renaming this and expanding it from the original idea of just having a manual circuit breaker. Here are the intended use cases:

* Make it easy to publish another message on certain exceptions -- cannot be coupled to cascading messages
* Have an option for discarding messages 
* Cannot lose messages when the listening agent is shut down. Try to defer all in flight messages in the buffered receiver

## Circuit Breaker / Kill Switch

### Trip Conditions

1. On a certain exception condition, trip it off. This is for the case Jeremy hit years ago where a downstream system would be up, but completely invalid, so you wanted to just immediately shut down any additional processing.
2. If a certain percentage of messages in a time window fail, shut down the circuit

### What to do when it trips off?

1. Send a message
2. Try to restart after a certain amount of time
3. Move all incoming messages to dead letter queue?
4. Shut down the listener?
5. Discard incoming messages

**Comment by jeremydmiller** [comment]
## Circuit Breaker Permutations

- [ ] Stay open w/ Rabbit MQ + Inline receiver
- [ ] Stay open w/ Rabbit MQ + buffered receiver
- [ ] Stay open w/ Rabbit MQ + durable receiver
- [ ] Shut and reopen w/ Rabbit MQ + Inline receiver
- [ ] Shut and reopen w/ Rabbit MQ + buffered receiver
- [ ] Shut and reopen w/ Rabbit MQ + durable receiver
- [ ] Shut and reopen w/ Parallelized Rabbit MQ + Inline receiver
- [ ] Shut and reopen w/ Parallelized Rabbit MQ + buffered receiver
- [ ] Shut and reopen w/ Parallelized Rabbit MQ + durable receiver
- [ ] Shut and reopen w/ Pulsar + Inline receiver
- [ ] Shut and reopen w/ Pulsar + buffered receiver
- [ ] Shut and reopen w/ Pulsar + durable receiver

**Comment by jeremydmiller** [comment]
## Punchlist

- [ ] Implement the `AlsoDo`
- [ ] Add recipe for sending a message as a response to a failure. 
- [ ] Documentation
