### ISSUE TITLE
1.0 Readiness

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#556]
## Build Automation

- [x] Put `ConcurrentCache` back into Baseline 2.*, or upgrade Marten to get Marten integration going again

## Documentation

- [ ] Move all HTTP related docs to JasperHttp
- [ ] Fix all code sample errors
- [ ] Remove all traces of `JasperHost` from the samples

## General

- [x] Eliminate all compiler warnings
- [x] Combine persistence and saga namespaces
- [ ] Reevaluate namespaces in the main library
- [x] Hunt down // TODO

**Comment by jeremydmiller** [comment]
## TODO Hunt

- [ ] Make `Envelope.EnsureData()` be internal. Might require a custom sending action block
- [ ] Do all the serialization for outgoing messages in `SendingAgent`. This will knock EnsureData() out as a public method
- [ ] `Envelope.Status` should be an enumeration
- [ ] Don't change the status through the property on envelope
- [ ] Same with Envelope.OwnerId
- [ ] Put a Polly retry wrapper around the call to send cascading messages? Do they all succeed or fail together? Looks like serialization issues are the only big blocker
- [ ] The "durable" local queue needs to be durable by default
- [ ] In MessagingRoot, have a property for the default durable queue where it's used for scheduled sends to avoid the lookups
- [ ] Use a new "scheduled" local queue for processing scheduled messages?
- [ ] TransportRuntime.Stop(), implement and use when shutting things down

**Comment by jeremydmiller** [comment]
This is duplicate with a lot of other things, and it's a grab bag. I'm closing.
