### ISSUE TITLE
JasperRegistry/JasperOptions usage improvements for integration with IConfiguration and IHostingEnvironment

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#557]
Look for every possible way to eliminate duplicated logic or more than one way of doing things. Focus on usability

// cc @CodingGorilla

**Comment by jeremydmiller** [comment]
As a first step, remove the `WorkerGraph` concept altogether. Lock it to one `IWorkerQueue` per queue listener. New configuration should allow you to directly configure the maximum number of threads per listener queue and the maximum message depth for back pressure

## Other ideas?

* Eliminate the *durable* nomenclature in Uri altogether.
* What is now `WorkerSettings` should become `ListenerSettings`, with a property for `IsDurable`
* Add a `Name` on `ListenerSettings` and use within logging?
* `JasperOptions.Listeners` needs to be a collection of `ListenerSettings`
* `JasperOptions.ListenFrom********()` should return the right instance of `ListenerSettings` 
* `WorkersGraph` goes away altogether

**Comment by jeremydmiller** [comment]
Latest idea: just use `IConfiguration` and `IHostEnvironment` within `JasperRegistry`. Assume that `JasperRegistry` is the sole way to configure Jasper options rather than also documenting `JasperOptions` within `Startup` classes, or loading directly from JSON.

## Tasks

- [ ] Eliminate all "ValueInConfig" lookup convenience methods in the JasperRegistry FI
- [ ] Stop loading `JasperOptions` from the config. Build JasperOptions directly in JasperRegistry
- [ ] Re-work `UseJasper()` methods as outlined later
- [ ] New overridable methods for `JasperRegistry`

## JasperRegistry methods

```
void Configure(IHostEnvironment hosting, IConfiguration config);
void ConfigureStaging(IConfiguration config);
void ConfigureProduction(IConfiguration config);
void ConfigureTesting(IConfiguration config);
void ConfigureDevelopment(IConfiguration config);
```

## UseJasper() signatures

```
UseJasper<T>(Action<T> customize = null) where T : JasperRegistry, new()
UseJasper(Action<JasperRegistry> = null)
UseJasper(JasperRegistry);
UseJasper(Action<HostBuilderContext, JasperRegistry> configure) 
```

**Comment by jeremydmiller** [comment]
Renaming this to "Improved JasperRegistry Mechanics" to get a win here.
