### ISSUE TITLE
New Endpoint configuration model for listeners and subscriptions

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#564]
Building off of #557 

## Ideas

* Eliminate usage of `Uri` to identify listeners and senders. It's good for unsecured TCP communication, but falls down on everything else
* Split out idea of "Endpoint"
* Remove `ReplyUri` concept? Might extend `Endpoint` model to expose a "ReplyEndpoint"???
* Envelope.Destination changes to be the endpoint name
* Overrides would take the endpoint name

## Endpoint concept

```
public abstract class Endpoint : IListenerSettings, IDisposable
{
    public bool ListeningEnabled {get; set;}

    public string Name {get;set;}

    // Might need to change up naming for consistency
    public abstract IListeningAgent CreateListener();
    public abstract ISender CreateSender();
}
```

**Comment by jeremydmiller** [comment]
## Updates on 11/19

* Ditch the `Endpoint` idea
* Let's try to eliminate the usage of *durable* anywhere in Uri values.
* Uri should **only** reference an address and have nothing else to do with configuration

**Comment by jeremydmiller** [comment]
Pretty close to giving up on this one altogether. It came out very differently in the mix. Can't really ditch the Uri idea because of replies if nothing else. The "durable" in the Uri is just too embedded to remove.

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Add new method on `IListenerConfiguration` to edit the whole execution options object
- [ ] Rename `ListenerSettings` to `Endpoint`
- [ ] Eliminate `Jasper.Messaging.Transports.Endpoint` because of the confusion. Will just inherit from the new `Endpoint`
- [ ] Make new `Endpoint` an abstract class with `Parse(Uri)` abstract method
- [ ] `LocalQueueSettings` gets the new `Parse(Uri)` method implementation. Blows up if invalid. Reads `durable` segment

**Comment by jeremydmiller** [comment]
Latest thoughts on syntax:

* Eliminate `JasperOptions.LocalQueues`
* New `IEndpoints` interface:

```
public interface IEndpoints
{
    // For checking things out
    Endpoint EndpointFor(Uri uri);
    IListenerConfiguration LocalQueueFor(string queueName);

    // Go with a nested closure. Thinking that this doesn't get used often
    void Publish(Action<PublishingExpression> configuration);

    // MOST of the time this should be the way folks use it
    // Lean on bus routing for most of the work. Topics as necessary
    ISenderConfiguration PublishAllMessagesTo(Uri uri);

    // More options

    // More options
    IListenerConfiguration ListenForMessagesFrom(Uri uri)
}
```

**Comment by jeremydmiller** [comment]
Feeling good about it now, but the next step is a whole lot of unit tests on the configuration

**Comment by jeremydmiller** [comment]
Kaboom! Took about 40 commits, but this is done.
