### ISSUE TITLE
Overhaul Rabbit MQ Transport

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#575]
It's broken, and add convenience methods for establishing listeners and senders against Rabbit MQ queues and topics

**Comment by jeremydmiller** [comment]
## Uri Pattern

1. For canonical Uri -> *rabbitmq://[exchange name]/[routing key]*
1. For reply uri where it's durable, append "durable" like so: *rabbitmq://[exchange name]/[routing key]/durable*
1. For "use whatever topic in publishing or sending", use `[topic]` as the routing key


## Tasks

- [ ] Comment out all failing acceptance tests and replace with `throw new NotImplementedException()` until everything compiles
- [ ] `RabbitMqEndpoint` can parse Uri pattern
- [ ] `RabbitMqEndpoint` can generate Reply Uri
- [ ] On `RabbitMqTransport`, model the exchanges, queues, and bindings
- [ ] `IHost.SetUpRabbitMq()` extension method that uses the line above
- [ ] `IHost.TearDownRabbitMq()` extension method 
- [ ] `IHost.PurgeRabbitMq()` extension method
- [ ] `RabbitMqTransport.AutoProvision` that does the above line
- [ ] New `rabbitmq` command, "setup" sub command
- [ ] New `rabbitmq` command, "purge" sub command
- [ ] New `rabbitmq` command, "teardown" sub command
- [ ] Set `ConnectionFactory.AutomaticRecoveryEnabled = true` by default!
