### ISSUE TITLE
Re-work PublishingExpression

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#577]
Some things aren't implemented. Others are duplicating Uri logic

**Comment by jeremydmiller** [comment]
Needs to incorporate the `ISenderSettings`, which is gonna change up the `ITransport` model. Mostly to specify durable/not durable, but might also impact batching

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Xml comments for everything
- [ ] Should be able to chain Message matching methods, like Message<Something>().Message<Else>().To()
- [ ] All `To()` methods should return an `ISenderSettings`

**Comment by jeremydmiller** [comment]
Folding this into #564
