### ISSUE TITLE
Message Tracker Testing Overhaul for 1.0

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#583]
Create a new feature to merely record the messages being sent? Thinking this would be the new "StubTransport" maybe.

**Comment by jeremydmiller** [comment]
## Ideas at the Moment

* Eliminate `MessageTracker` in favor of using a newly improved `MessageHistory` and recording `IMessageLogger`
* "Stub" transport should be used merely to record outgoing messages
* new `MessageHistory` mode should be smart enough to understand which messages need to be waited on and which don't
* Only try for a local, one application model right now?

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Replace old MessageTracker with more generic model
- [ ] Write unit tests on the new "find" methods on `TrackingSession`
- [ ] Capture the system name on the EnvelopeRecords
- [ ] New `JasperOptions.Endpoints.StubAllExternallyOutgoingEndpoints()` method
