### ISSUE TITLE
Replace JasperOptions.Settings with configurable Extensions

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#586]
Eliminate JasperOptions.Settings and all of that.

Prefer a new `JasperOptions.Extensions`, with a new `Include<T>(Action<T> configure = null)` option that would effectively take its place

This just continues the theme of replacing perfectly functional FubuMVC-esque code with more idiomatic ASP.Net Core usage

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] New `IExtensions` interface and `JasperOptions.Extensions` hive property just to facilitate extension methods
- [ ] Decouple Marten extensions from custom Settings usage
- [ ] Decouple Sql Server extensions from custom Settings usage
- [ ] Rip out all the old Settings code.
