### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#646]
# This is it! 

- [x] All xUnit tests passing
- [x] All Storyteller tests passing
- [x] Clean up splash pages in docs
- [x] Publish docs
- [x] Publish nugets
- [x] Update all samples to Jasper 1.0 and .Net Core 3.1
- [x] Publish template nuget
