### ISSUE TITLE
Resuscitate Jasper HTTP support

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#653]
Bring back the Jasper HTTP handler stuff as an extension library. This will grow in time to be something that works much more closely with Jasper's command execution to be a coherent CQRS skeleton architecture.

## Tasks

- [x] Import old JasperHttp code and get it to compile
- [x] Delete Router and related types
- [x] Import old JasperHttp.Testing code and get it to compile
- [x] Get unit tests passing, but delete any tests that are no longer relevant
- [x] Review `JasperHttpExtensions`
- [x] Switch to using Endpoint routing
- [x] Get all unit tests passing
- [x] Add Nuget publishing to the build
- [x] Add unit tests to the build
- [x] Figure out what to do about the ASP.net MVC Compliance. May no longer be valuable
- [x] Make it configurable whether MVC Controllers are used as Jasper endpoints or not. Make it opt in
- [x] Unit Test Spread.RoutePatternPath()
- [x] Unit Test RouteArgument.RoutePatternPath() w/ type constraints

**Comment by jeremydmiller** [comment]
Will need to test the HTTP routes later with the code generation diagnostics

**Comment by jeremydmiller** [comment]
Need to solve the "do we include controllers or not" and also, what if you have simple parameters that have to be route args that aren't part of the route?
