### ISSUE TITLE
Use the new LamarCodeGeneration "Auto" type generation

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#695]

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Implement ICodeFile in HandlerChain
- [ ] Implement ICodeFileCollection in HandlerGraph
- [ ] Test with Auto on
- [ ] Test from command line generating everything
