### ISSUE TITLE
Rabbit Mq AutoPurgeOnStartup should be configurable on an endpoint by endpoint basis

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#714]
Support a global purge and an endpoint by endpoint purge

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] AutoPurge property on RabbitMqEndpoint
- [ ] FI support to set that
- [ ] Prove that it does the purge on first usage
- [ ] Also does purge on global purge
